# Basic
title: Sniff Kevin
subtitle: Travel By the Moon
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Sniff Kevin's Tiny Word's World.
creator: <a href="http://qiukexu.cn">@winstars</a>

url: "http://my.qiukexu.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: winstars
    # duoshuo: 
    
# Social
social:
    weibo: zxiaoqi
    github: winstars
    twitter: winstars
    gplus: 107108267983477358170
    mail: winstars@qiukexu.cn

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
